ChươngChinh/TracNghiemOnline/TracNghiemOnline/Areas/Admin/Controllers/LoginAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TracNghiemOnline.Modell;

namespace TracNghiemOnline.Areas.Admin.Controllers
{
    public class LoginAdminController : Controller
    {
        // GET: Admin/Login
        public ActionResult Login()
        {
            Session[ComMon.ComMonStants.UserLogin] = null;
            return View();
        }
        
        public ActionResult DangNhap(TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                var TK = new Modell.Dao.LoginDao().Login(taiKhoan);
                if (TK != null)
                {
                    Session.Add(ComMon.ComMonStants.UserLogin, TK);
                    if (TK.ChưcVu.Equals("Cán Bộ"))
                    {
                        return RedirectToAction("DSDETHI", "Home");

                    }
                    else if (TK.ChưcVu.Equals("Admin"))
                    {
                        return RedirectToAction("DSDETHI", "Admin");

                    }
                    else if (TK.ChưcVu.Equals("BoMon")) return RedirectToAction("DSDethi", "Bomon");


                    return Redirect("/LopHocPhan");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng Nhập Không Đúng ");
                }

            }
            return View("Login");
        }
    }
}

ChươngChinh/TracNghiemOnline/TracNghiemOnline/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using TracNghiemOnline.Modell;

namespace TracNghiemOnline.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login

        public ActionResult Login()
        {
            Session[ComMon.ComMonStants.UserLogin] = null;
            return View();
        }
        public ActionResult DangNhap(TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                var TK = new Modell.Dao.LoginDao().Login(taiKhoan);
                if (TK != null)
                {
                    Session.Add(ComMon.ComMonStants.UserLogin, TK);
                    if (TK.ChưcVu.Equals("Cán Bộ"))
                    {
                        return RedirectToAction("DSDETHI", "Admin/Home");

                    }
                    else if (TK.ChưcVu.Equals("Admin"))
                    {
                        return RedirectToAction("DSDETHI", "Admin/Admin");

                    }
                    else if (TK.ChưcVu.Equals("BoMon")) return RedirectToAction("DSDethi", "Admin/Bomon");

                    return RedirectToAction("LopHocPhan", "TrangChu");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng Nhập Không Đúng ");
                }

            }
            return View("Login");
        }
    }
}

ChươngChinh/TracNghiemOnline/TracNghiemOnline/Areas/Admin/Views/LoginAdmin/Login.cshtml
@model TracNghiemOnline.Modell.TaiKhoan
<html lang="zxx">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport">
    <link rel="icon" href="~/assets/img/icon.ico" type="image/x-icon">

    <!-- Fonts and icons -->
    <script src="~/assets/js/plugin/webfont/webfont.min.js"></script>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:300,400,700,900" media="all">
    <link rel="stylesheet" href="~/assets/css/fonts.min.css" media="all">
    <script>
        WebFont.load({
            google: { "families": ["Lato:300,400,700,900"] },
            custom: { "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['../../assets/css/fonts.min.css'] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/atlantis.min.css">
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="~/assets/css/demo.css">
</head>
<body>
    <div class=" position-relative " style="top:20%">
        <div class="col-md-4 ml-auto mr-auto">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title text-center">ĐĂNG NHẬP</h4>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("DangNhap", "LoginAdmin", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <label>Tên đăng nhập:</label>
                            @Html.TextBoxFor(model => model.TenDangNhap, new { @class = "form-control", @autofocus = "autofocus", placeholder = "Enter Username" })
                            @Html.ValidationMessageFor(model => model.TenDangNhap, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Mật khẩu:</label>
                            @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", type = "password", placeholder = "Enter Password" } })
                            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group ">
                            <button class="btn btn-primary col-12" id="vao" type="submit">Đăng nhập</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</body>


</html>


<noembed>