ChươngChinh/TracNghiemOnline/TracNghiemOnline/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using TracNghiemOnline.ComMon;
using TracNghiemOnline.Model;
//using System.Windows.Forms;
using TracNghiemOnline.Modell;
using TracNghiemOnline.Modell.Dao;

namespace TracNghiemOnline.Controllers
{
    public class TrangChuController : BaseController
    {
        // GET: TrangChu
        public void CapNhatDuLieu(string tgbd)
        {
            try {
                string[] ngay = tgbd.Split('/');
                DateTime dateTime = new DateTime(int.Parse(ngay[0]), int.Parse(ngay[1]), int.Parse(ngay[2]), int.Parse(ngay[3]), int.Parse(ngay[4]), int.Parse(ngay[5]));
                Session["Gio"] = dateTime;
            }
            catch
            {

            }
          
           
        }
        public ActionResult Index(string id)
        {

            LopHocPhan lopHoc = new TracNghiemOnlineDB().LopHocPhans.Find(id);
            Session["LopHP"] = lopHoc;
            var session = (TaiKhoan)Session[ComMonStants.UserLogin];
            foreach (var item in new TracNghiemOnlineDB().Chuong_Hoc.Where(x => x.Ma_Mon == lopHoc.MaMon && x.TrangThai == 1))
            {
                if (!new TracNghiemOnlineDB().DS_BaiHoc.Select(x => x).ToList().Exists(x => x.Ma_Bai == item.Ma_Chuong && x.MaSV.Equals(session.TaiKhoan1)))
                {

                    TracNghiemOnlineDB tracNghiemDB = new TracNghiemOnlineDB();
                    tracNghiemDB.DS_BaiHoc.Add(new DS_BaiHoc()
                    {
                        SoCauSai = 0,
                        Ma_Bai = item.Ma_Chuong,
                        MaSV = session.TaiKhoan1,
                        SoCauDung = 0,
                        ListCauHoi = ""

                    });
                    tracNghiemDB.SaveChanges();
                }

            }

            return View(new TracNghiemOnlineDB().Chuong_Hoc.Where(x => x.Ma_Mon == lopHoc.MaMon && x.TrangThai == 1));
        }

        [HttpGet]
        
      
        public ActionResult Phong()
        {
            TracNghiemOnlineDB db = new TracNghiemOnlineDB();
            var session = (TaiKhoan)Session[ComMon.ComMonStants.UserLogin];
            var phong = db.DS_SVThi.Where(x => x.Ma_SV.Equals(session.TaiKhoan1) && !x.TrangThai.Equals("Đã Nộp"));
            List<Phong_Thi> phong_This = new List<Phong_Thi>();
            foreach (var item in phong)
            {
                if(new TracNghiemOnlineDB().Phong_Thi.Where(x=>x.MaPhong.Equals(item.MaPhong)&& !x.TrangThai.Equals("Đã Đóng") && x.Xoa==true) != null)
                {
                    phong_This.AddRange(new TracNghiemOnlineDB().Phong_Thi.Where(x => x.MaPhong.Equals(item.MaPhong) && !x.TrangThai.Equals("Đã Đóng") && x.Xoa == true));
                }
            }
            return View(phong_This);

        }
      public  int HuyDe(long madethi1,string tgbd)
        {
            var ngay = tgbd.Split('/');
            TracNghiemOnlineDB db = new TracNghiemOnlineDB();
            var dethi = db.De_Thi.Find(madethi1);
            if (dethi.dem == null) { dethi.dem = 0; }
            dethi.dem++;

            db.SaveChanges();
            DateTime data = new DateTime(int.Parse(ngay[0]), int.Parse(ngay[1]), int.Parse(ngay[2]), int.Parse(ngay[3]), int.Parse(ngay[4]), int.Parse(ngay[5]));
            //    dethi.TrangThai = false;
         //   dethi.CT_Dethi = dethi.CT_Dethi + "D";
            CT_Dethi cT = new CT_Dethi();
            cT.MADETHI = madethi1;
            cT.LYDO =  "Sinh viên đã rời khỏi màn hình lúc "+data.ToString();
           
            db.CT_Dethi.Add(cT);
            db.SaveChanges();
        //    TracNghiemOnlineDB = new TracNghiemOnlineDB();
            var ds = db.DS_SVThi.SingleOrDefault(x=>x.MaDeThi==madethi1);
            ds.TrangThai = "Đã chuyển tab";
            db.SaveChanges();
            return dethi.dem.Value;
        }

        public string Refresh(long madethi1, string tgbd)
        {
            var ngay = tgbd.Split('/');
            TracNghiemOnlineDB db = new TracNghiemOnlineDB();
            DateTime data = new DateTime(int.Parse(ngay[0]), int.Parse(ngay[1]), int.Parse(ngay[2]), int.Parse(ngay[3]), int.Parse(ngay[4]), int.Parse(ngay[5]));
            CT_Dethi cT = new CT_Dethi();
            cT.MADETHI = madethi1;
            cT.LYDO = " Mất kết nối " + data.ToString();
            db.CT_Dethi.Add(cT);
            db.SaveChanges();
            //    TracNghiemOnlineDB = new TracNghiemOnlineDB();
            var ds = db.DS_SVThi.SingleOrDefault(x => x.MaDeThi == madethi1);
            ds.TrangThai = "Mất kết nối";
            db.SaveChanges();
            return ds.MaPhong;
        }

        public int Refresh1(long madethi1)
        {
            
            TracNghiemOnlineDB db = new TracNghiemOnlineDB();
            //    TracNghiemOnlineDB = new TracNghiemOnlineDB();
            var ds = db.DS_SVThi.SingleOrDefault(x => x.MaDeThi == madethi1);
            ds.TrangThai = "Đang làm bài";

            db.SaveChanges();
            return 0;
        }

        public void TGTHI(string tgbd)
        {
            Session["TGTHI"] = tgbd;

        }
        public ActionResult DSDETHI() {

            List<DanhGia> ketQuas = new List<DanhGia>();
            TracNghiemOnlineDB db = new TracNghiemOnlineDB();
            var session = (TaiKhoan)Session[ComMon.ComMonStants.UserLogin];
          
            var dssv = db.DS_SVThi.Where(x => x.Ma_SV.Equals(session.TaiKhoan1));

            List<Phong_Thi> phong_This = new List<Phong_Thi>();

            foreach (var item in dssv)
            {
                try
                {

                    var phong = new TracNghiemOnlineDB().Phong_Thi.Where(x => x.MaPhong.Equals(item.MaPhong) && x.TrangThai.Equals("Đã Đóng"));
                    if (phong != null)
                    {
                        var DeThi = db.De_Thi.Where(x => x.MaDeThi == item.MaDeThi).ToList().First();
                        if (DeThi != null)
                        {
                            if (DeThi.KetQuaThis.Count == 0)
                            {
                                TracNghiemOnlineDB tb1 = new TracNghiemOnlineDB();
                                DanhGia danhGia = new DanhGia();
                                danhGia = new QuanLyThiDAO().Mark(DeThi);

                                KetQuaThi ketQuaThi = new KetQuaThi();
                                ketQuaThi.Ma_DeThi = DeThi.MaDeThi;

                                ketQuaThi.NgayThi = phong.ToList()[0].ThoiGianDong;
                                ketQuaThi.SoCauDung = danhGia.ketQuaThi.SoCauDung;
                                ketQuaThi.SoCauSai = danhGia.ketQuaThi.SoCauSai;
                                ketQuaThi.DiemSo = danhGia.ketQuaThi.DiemSo;
                                tb1.KetQuaThis.Add(ketQuaThi);
                                tb1.SaveChanges();

                                foreach (var item1 in danhGia.ketQuaThi.De_Thi.Danh_Gia)
                                {
                                    Danh_Gia danh_Gia = new Danh_Gia();

                                    danh_Gia.MaChuong = item1.MaChuong;
                                    danh_Gia.MaDeThi = item1.MaDeThi;
                                    danh_Gia.SoCauDung = item1.SoCauDung;
                                    danh_Gia.TongCau = item1.TongCau;
                                    //  danh_Gia.NhanXet = item1.NhanXet;
                                    danh_Gia.DanhGia = item1.DanhGia;
                                    tb1.Danh_Gia.Add(danh_Gia);

                                    tb1.SaveChanges();
                                }

                                ketQuas.Add(danhGia);
                            }
                            else
                            {
                                DanhGia danhGia = new DanhGia();
                                danhGia.ketQuaThi = DeThi.KetQuaThis.ToList().First();
                                danhGia.ketQuaThi.NgayThi = phong.ToList()[0].ThoiGianDong;
                                danhGia.ketQuaThi.De_Thi = DeThi;
                                ketQuas.Add(danhGia);

                            }
                            phong_This.Add(phong.ToList()[0]);

                        }
                    }
                }
                catch { }
            }

                
            
            ViewBag.phong=phong_This;
           
            return View(ketQuas);
        }
       
        public ActionResult TinhDiem(long id)
        {
            ViewBag.id = id;
            return View();
        }

        public ActionResult LopHocPhan() {
            TracNghiemOnlineDB db = new TracNghiemOnlineDB();
            var session = (TaiKhoan)Session[ComMon.ComMonStants.UserLogin];
            var dsphong = db.DS_LopHP.Where(x => x.MA_SV.Equals(session.TaiKhoan1.Trim()));
            List<LopHocPhan> lop = new List<LopHocPhan>();

            foreach (var item in dsphong)
            {
                if(new TracNghiemOnlineDB().LopHocPhans.Where(x => x.MaLop.Equals(item.Ma_LOP)) != null)
                {
                    lop.AddRange(new TracNghiemOnlineDB().LopHocPhans.Where(x => x.MaLop.Equals(item.Ma_LOP)));

                }

            }


            
            return View(lop);
        }
     
        public ActionResult Loald(string id)
        {
            string tgbd = (string)Session["TGTHI"];
            var ngay = tgbd.Split('/');
            var session = (TaiKhoan)Session[ComMon.ComMonStants.UserLogin];
            var list = new BoDeDao().ChapterStudy(long.Parse(id));
            var Exem = new De_Thi();
            try
            {
                Exem = (De_Thi)Session[ComMon.ComMonStants.ExamQuesTion];


                if (Exem == null)
                {

ChươngChinh/TracNghiemOnline/TracNghiemOnline/Views/Share/LayOutHome.cshtml
<!DOCTYPE html>
<html lang="en-US" dir="ltr" class="chrome windows">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Trắc nghiệm online</title>
    <meta name="theme-color" content="#ffffff">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

    <script type="text/javascript" async
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>
    <style>
        #particles1 {
            width: 100%;
            height: 100%;
            top: 0;
            bottom: 0;
            overflow: hidden;
            left: 0;
            right: 0;
            position: fixed;
            z-index: 100;
            overflow: hidden;
            text-align: center;
        }
    </style>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link href="~/Content/Layout/css/theme.css" rel="stylesheet" />
</head>
<body>
    <div id="particles1">
        <div style="margin-top:15%">
            <img src="~/Content/Img/5.gif" />
        </div>
    </div>
    <main class="main" id="top">
        @Html.Action("Menu", "TrangChu")
        @RenderBody()
        <section class="py-3 pb-0">

            <div class="container">
                <hr class="opacity-100" style="color:rgb(16,95,197)">

            </div>
            <!-- end of .container-->

        </section>


    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>


    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,300;1,700;1,900&amp;display=swap" rel="stylesheet">

    @RenderSection("Jsfooter", required: false)
    @RenderSection("scripts", required: false)
    <script>

        $(document).ready(function () {
            var now = new Date();
            //var now = TaoNgay(ngay, thoigian);
            var tgbd = now.getFullYear() + '/' + (now.getMonth() + 1) + '/' + now.getDate() + '/' + now.getHours() + '/' + now.getMinutes() + '/' + now.getSeconds() + ""

            $.ajax({
                url: '/TrangChu/CapNhatDuLieu',
                type: 'post',
                data: { tgbd: tgbd },
                success: function (data) {
                    $('#particles1').hide();

                }

            });

        })



    </script>
</body>
</html>
<noembed>

ChươngChinh/TracNghiemOnline/TracNghiemOnline/Views/Share/LayOutLopHocPhan.cshtml
@{
    Layout = null;
    LopHocPhan hocPhan = (LopHocPhan)Session["LopHP"];
}
@using TracNghiemOnline.Modell;
@using TracNghiemOnline.Modell.Dao;
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/new_logo.png">
    <link rel="icon" type="image/png" href="~/assets/img/new_logo.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        Đánh Gía Kiến Thức Vật Lý Trung Học Phổ Thông
    </title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <!-- CSS Files -->
    <link href="~/assets/css/material-dashboard.css?v=2.1.2" rel="stylesheet" />
    <style>
        #DongHo {
            position: fixed;
            top: 10%;
            left: 81.5%;
            height: 100%;
            cursor: pointer;
            z-index: 99;
        }
        #particles1{
            width: 100%;
            height: 100%;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            position: absolute;
            z-index: 101;
            overflow: hidden;
           text-align:center;

        }

        #dialog{
            width: 100%;
            height: 100%;
            top: 0;
            bottom: 0;
            overflow: hidden;
            left: 0;
            right: 0;
            position: absolute;
            z-index: 100;
            overflow: hidden;
            text-align: center;
            background-color:rgb(68 65 65 / 0.55);

        }
        #particles {
            width: 100%;
            height: 100%;
            overflow: hidden;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            position: absolute;
            z-index: -2;
            background-image: linear-gradient(rgb(247 247 247), rgb(255 255 255 / 0.80));

            @*background-image: linear-gradient(rgb(238 238 238 / 0.60), rgb(255 255 255 / 0.00));*@
        }
        .particles {
            width: 100%;
            height: 100%;
            overflow: hidden;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            position: absolute;
            z-index: 1;
          
        }

        .Narlink {
            background-image: linear-gradient(#f8051d, rgb(255 150 75 / 0.88));
        }


        .form-check-label {
            cursor: pointer;
        }
        .sidebar {
            width:260px;
        }
    </style>
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <!-- CSS only -->

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

    <script type="text/javascript" async
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <!-- JavaScript Bundle with Popper -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

</head>
<body class="particles" id="demo" style="background-color:rgb(255 255 255 / 0.90)">
    <div id="thongbao">

    </div>


    <div class="wrapper ">

        <div class="sidebar" data-image="../assets/img/sidebar-3.jpg">
            <!--
                Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

                Tip 2: you can also add an image using data-image tag
            -->
            <div class="logo">
                <a href="#" class="simple-text logo-normal">
                    Trắc Nghiệm Online
                </a>
            </div>
            <div class="sidebar-wrapper active Narlink1">
                <ul class="nav">

                    <li class="nav-item">
                        <a class="nav-link" id="hocbai" href="/LopHoc/@hocPhan.MaLop">
                            <i class="material-icons">library_books</i>

                            <p>Học Bài</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="onbai" href="/LopHP/OnTap">
                            <i class="bi bi-book"></i>
                            <p>Ôn Tập</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" id="quanly" href="/LopHP/QuanLy">
                            <i class="material-icons">content_paste</i>
                            <p>Quản Lý Học Tập</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="danhgia" href="/LopHP/DanhGia">
                            <i class="bi bi-graph-up"></i>
                            <p>Đánh Gía Kết Qủa</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="lienhe" href="/LopHocPhan">
                            <i class="bi bi-arrow-left-square"></i>
                            <p>Quay về</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">

          
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>

            </div>
        </div>

    </div>


    <div id="particles" class="particles"></div>
    <div id="particles1">
        <div style="margin-top:15%">
            <img src="~/Content/Img/5.gif" />
        </div>
    </div>


    <!--   Core JS Files   -->
    @Scripts.Render("~/bundles/jquery")

   
    <script src="~/assets/js/plugin/perfect-scrollbar.jquery.min.js"></script>

    <script src="~/assets/js/plugin/chartist2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#particles1').hide();
            $('#thongbao').hide();
        })

    </script>

    <script src="~/assets/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
-->

    @RenderSection("scripts", required: false)
</body>



</html>

ChươngChinh/TracNghiemOnline/TracNghiemOnline/Views/Share/layoutBaithi.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/new_logo.png">
    <link rel="icon" type="image/png" href="~/assets/img/new_logo.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        Đánh Gía Kiến Thức Vật Lý Trung Học Phổ Thông
    </title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <!-- CSS Files -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

    <script type="text/javascript" async
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>

    <style>
        #DongHo {
            position: fixed;
            top: 10%;
            left: 81.5%;
            height: 100%;
            cursor: pointer;
            z-index: 99;
        }
        #particles1{
            width: 100%;
            height: 100%;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            position: absolute;
            z-index: 101;
            overflow: hidden;
           text-align:center;

        }

        #dialog{
            width: 100%;
            height: 100%;
            top: 0;
            bottom: 0;
            overflow: hidden;
            left: 0;
            right: 0;
            position: absolute;
            z-index: 100;
            overflow: hidden;
            text-align: center;
            background-color:rgb(68 65 65 / 0.55);

        }
        #particles {
            width: 100%;
            height: 100%;
            overflow: hidden;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            position: absolute;
            z-index: -2;
            background-image: linear-gradient(rgb(247 247 247), rgb(255 255 255 / 0.80));

            @*background-image: linear-gradient(rgb(238 238 238 / 0.60), rgb(255 255 255 / 0.00));*@
        }
        .particles {
            width: 100%;
            height: 100%;
            overflow: hidden;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            position: absolute;
            z-index: 1;
         /* //  background-image: url('../../assets/img/hinh-anh-thac-nuoc-dep-14-1.jpg');*/
        }

        .Narlink {
            background-image: linear-gradient(#f8051d, rgb(255 150 75 / 0.88));
        }


        .form-check-label {
            cursor: pointer;
        }
    </style>

    <!-- CSS only -->
    <link href="~/assets/css/material-dashboard.css" rel="stylesheet" />

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <!-- JavaScript Bundle with Popper -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="http://sibeeshpassion.com/content/scripts/jquery-1.11.1.min.js"></script>
</head>

    <body  id="demo1" style="background-color:rgb(255 255 255 / 0.90)" oncontextmenu="return false" onselectstart="return false" ondragstart="return false">
        <div id="thongbao">

        </div>

        @RenderBody()

  

        <div id="particles" class="particles"></div>


        <!--   Core JS Files   -->
        @Scripts.Render("~/bundles/jquery")
    

        @RenderSection("scripts", required: false)
    </body>



</html>